title: Zhiyuan Xu
url: "https://xuzhiyuan1528.github.io/"
# baseurl: "/about"

markdown: kramdown
ins_logo: "./ecs_logo.png"
logo_url: "http://eng-cs.syr.edu/"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_main: "Copyright © 2019 Zhiyuan Xu. All Rights Reserved. Theme by "
footer_text: "ankitsultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Publications"
   link: "pub"
 - name: "Research"
   link: "res"
